title: Paxton Fitzpatrick
description: >-
  My personal website
baseurl: ""
url: https://paxtonfitzpatrick.me
lang: en_US
year_created: 2020
year_last_updated: 2022

author: Paxton Fitzpatrick
email: Paxton.C.Fitzpatrick.GR@Dartmouth.edu
address: 416 Moore Hall, Dartmouth College<br>Hanover, NH 03755
github: https://github.com/paxtonfitzpatrick
linkedin: https://www.linkedin.com/in/paxtonfitzpatrick
twitter: https://twitter.com/paxt0n4
google_scholar: https://scholar.google.com/citations?user=0Pvr9WEAAAAJ
cv_path: assets/files/CV-paxton-fitzpatrick.pdf
google_analytics:
  id: UA-169319829-1
  enabled: true

# Jekyll build settings
theme: null
safe: true
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .idea
  - node_modules
