title: Paxton Fitzpatrick
description: >-
  My personal website
baseurl: ""
url: https://paxtonfitzpatrick.me
lang: en_US
year_created: 2020
year_last_updated: 2022

author: Paxton Fitzpatrick
google_analytics:
  id: UA-169319829-1
  enabled: true

# Jekyll build settings
theme: null
safe: true
timezone: America/New_York
verbose: false
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - node_modules/
  - scratch/
  # dotfiles are excluded from build by default, but edits to them still trigger
  # rebuild via jekyll-watch when running jekyll serve or jekyll build --watch
  # unless explicitly listed here (jekyll-watch also appears not to handle glob
  # patterns here even though site.exclude supports them)
  - .DS_Store
  - .eslintrc.js
  - .gitignore
  - .jekyll-metadata
  - .ruby-version
  - .stylelintrc.js
  - .idea/
